name: TempleCraft
author: Mike Singleton
main: com.msingleton.templecraft.TempleCraft
version: 0.42
commands:
  tc:
    description: Base command for TempleCraft
    usage: |
           /tc - List commands you have permission to use.
permissions:
    templecraft.*:
        description: Gives access to all TempleCraft commands
        children:
            templecraft.tc: true
            templecraft.newgame: true
            templecraft.join: true            templecraft.leave: true            templecraft.ready: true            templecraft.templelist: true            templecraft.playerlist: true            templecraft.forcestart: true            templecraft.forceend: true
            templecraft.enable: true
            templecraft.checkupdates: true
            templecraft.newtemple: true
            templecraft.deletetemple: true
            templecraft.edittemple: true
            templecraft.editall: true
            templecraft.savetemple: true
            templecraft.worldtotemple: true
            templecraft.converttemples: true
            templecraft.placesigns: true
            templecraft.renametemple: true
            templecraft.setmaxplayers: true
            templecraft.findsigblocks: true

    templecraft.editbasics:
        description: Gives access to basic edit commands
        children:
            templecraft.join: true
            templecraft.newgame: true
            templecraft.newtemple: true
            templecraft.edittemple: true
            templecraft.savetemple: true
            templecraft.addplayer: true
            templecraft.removeplayer: true

# General Play Commands
    templecraft.tc:
        description: Default Command for TempleCraft.
        default: true
    templecraft.newgame:
        description: Create a new game.
        default: op
    templecraft.join:
        description: Join an open game.
        default: true
    templecraft.leave:
        description: Leave current game.
        default: true
    templecraft.ready:
        description: Lists who is ready.
        default: true
    templecraft.templelist:
        description: Lists all Temples.
        default: true
    templecraft.gamelist:
        description: Lists all current games.
        default: true
    templecraft.playerlist:
        description: Lists all players in a Temple.
        default: true
    templecraft.forcestart:
        description: Starts the Temple.
        default: op
    templecraft.forceend:
        description: Ends the Temple.
        default: op

# Temple Edit Commands
    templecraft.newtemple:
        description: Allows Creating New Temples.
        default: true
    templecraft.deletetemple:
        description: Allows Deletion of Temples.
        default: op
    templecraft.edittemple:
        description: Allows Editing Temples.
        default: true
    templecraft.addplayer:
        description: Allows Adding Players Access to Edit Temple.
        default: true
    templecraft.removeplayer:
        description: Allows Removing Players Access to Edit Temple.
        default: true
    templecraft.editall:
        description: Allows Editing & Adding/Removing of players in Any Temple.
        default: op
    templecraft.savetemple:
        description: Allows Saving the current Temple.
        default: true
    templecraft.worldtotemple:
        description: Save a world as a temple.
        default: op
    templecraft.converttemples:
        description: Converts .tcf files to worlds and sets them up if possible.
        default: op
    templecraft.renametemple:
        description: Rename a temple.
        default: op
    templecraft.setmaxplayers:
        description: Set the maximum number of players allowed in a temple per game.
        default: op
# Other Commands
    templecraft.checkupdates:
        description: Allows Checking for Updates.
        default: op
    templecraft.placesigns:
        description: Allows placing signs for TempleCraft purposes.
        default: op
    templecraft.findsigblocks:
        description: Allows finding significant blocks in temples.
        default: op